using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ResumeScreeningAgent.Models;

namespace ResumeScreeningAgent.Services;

public class ReportService
{
    public string GenerateRankingReport(
        List<Candidate> candidates)
    {
        string reportsFolder =
            Path.Combine(
                Directory.GetCurrentDirectory(),
                "Reports");

        Directory.CreateDirectory(
            reportsFolder);

        string filePath =
            Path.Combine(
                reportsFolder,
               $"CandidateRankingReport_{DateTime.Now:yyyyMMdd_HHmmss}.pdf");

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);

                page.Header()
                    .Text("Resume Screening Report")
                    .FontSize(20)
                    .Bold();

                page.Content()
                    .Column(column =>
                    {
                        foreach (Candidate candidate in candidates)
                        {
                            column.Item()
                                .PaddingBottom(15)
                                .BorderBottom(1)
                                .Column(item =>
                                {
                                    item.Item()
                                        .Text(
                                            $"Rank: {candidate.Rank}")
                                        .Bold();

                                    item.Item()
                                        .Text(
                                            $"Name: {candidate.Name}");

                                    item.Item()
                                        .Text(
                                            $"Score: {candidate.Score}");

                                    item.Item()
                                        .Text(
                                            $"Recommendation: {candidate.Recommendation}");

                                    item.Item()
                                        .Text(
                                            $"Matched Skills: {string.Join(", ", candidate.MatchedSkills)}");

                                    item.Item()
                                        .Text(
                                            $"Missing Skills: {string.Join(", ", candidate.MissingSkills)}");
                                });
                        }
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by Resume Screening Agent");
                    });
            });
        })
        .GeneratePdf(filePath);

        return filePath;
    }
}